name: mocha
on:
  push:
    branches-ignore:
      - main
jobs:
  mocha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: ci
        run: yarn install --immutable --immutable-cache --check-cache
      - name: build
        run: yarn build
      - name: mocha
        run: yarn test
