name: Vitest
on: push
jobs:
  Vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Config
        run: cp config/config.json.sample config/config.json && cp config/encode_settings.json.sample config/encode_settings.json && yarn migrate
      - name: Vitest
        run: yarn test
