name: Vitest
on: push
jobs:
  Vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Set Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Config
        run: cp config/config.json.sample config/config.json && cp config/encode_settings.json.sample config/encode_settings.json && yarn migrate
      - name: Vitest
        run: yarn test
